### PR TITLE
Add configuration field to support https.Agent setup #27

### PR DESCRIPTION
**Pull request by stathopou**

### CODE REVIEW

**Comment by brandonhamilton** [comment]
Thanks for this!

Should the default value for the `agent` option to `http.request` be an empty object ?
The [documentation](https://nodejs.org/docs/latest-v10.x/api/http.html#http_http_request_url_options_callback) indicates that the `agent` option should be either an `http.Agent` instance, a `boolean` or `undefined` (default).

**Comment by stathopou** [comment]
Indeed, maybe setting the field to undefined should be the best option, just to keep the client intact. Update coming up soon.

**Comment by brandonhamilton** [comment]
Awesome! Thanks again for this 👍

**Comment by stathopou** [comment]
Thank you for this useful module!! In my use case, I also had to replace the default /write endpoint with a custom one, which leads to a proxy. If you think that it would be useful to customize the client's target url. I could contribute with that.

**Pull request merged**
