### PR TITLE
All in one: namer, callback, reported hook, NaN fix

### PR DESCRIPTION
**Pull request by holyjak**
An alternative to merging #14, #15, #16, #17, this has them all merged (and solved the 2 simple merge issues).

### CODE REVIEW

**Comment by brandonhamilton** [comment]
Thank you! This is great

**Comment by holyjak** [comment]
Thanks a lot for the quick acceptance! Any estimate when can this be released? Thanks!

**Comment by brandonhamilton** [comment]
It has been released as [v0.2.1](https://github.com/brandonhamilton/node-metrics-influxdb/releases/tag/v0.2.1) in the [npm registry](https://www.npmjs.com/package/metrics-influxdb)

**Comment by holyjak** [comment]
Thanks a lot!
tir. 19. sep. 2017 kl. 10.35 skrev Brandon Hamilton <
notifications@github.com>:

**Pull request merged**
